version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: acadenic_web
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    # depends_on:
    #   - db
    # environment:
    #   - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    #   - DJANGO_SETTINGS_MODULE=acadenic_web.settings.dev
    #   - SECRET_KEY=secret
    #   - DEBUG=True
    #   - ALLOWED_HOSTS=*
    #   - EMAIL_HOST=smtp.gmail.com
    #   - EMAIL_PORT=587
    #   -